### ISSUE TITLE
Use conditions system to share ACTS calculation objects

### ISSUE THREAD

**Issue by tomeichlersmith** [LDMX-Software/Tracking#16]
@pbutti putting stuff here so it doesn't get lost in slack.

### Goal
Pass around `Acts::TrackingGeometry` between processors using the conditions system. If we get this working, then there are a multitude of other calculation objects that would be helpful to pass around (e.g. `Acts::GeometryContext`, `Acts::CalibrationContext`, and `Acts::MagneticFieldContext`).

### Notes on Building
ldmx working branch: tracking_dev
acts working branch: pbutti:cubvolbld-ldmx (https://github.com/pbutti/acts/tree/cubvolbld-ldmx)
- Start docker
- `source ldmx-sw/scripts/ldmx-env.sh`
- Load the acts image `ldmx pull dev sha-995b3239`
- Build acts in container
- Recompile ldmx-sw using the pre-installed acts dependency
```
ldmx bash
cd ldmx-sw/build/
rm -rf *
source /full/path/to/acts/install/bin/this_acts.sh
cmake -DActs_DIR=/full/path/to/acts/install/lib/cmake/Acts ..
make -j 4 install
```
- Compile the Tracking module only
cd build; make Tracking; cp Tracking/libTracking.so ../install/lib/libTracking.so; cd ..

#### Troubule Shoot
In the case the compilation fails
```
cd ${LDMX_BASE}/ldmx-sw/build/Detectors 
/deps/dd4hep/bin/listcomponents_dd4hep -o libTracker.components ${LDMX_BASE}/ldmx-sw/install/lib/libTracker.so
```

**Comment by pbutti** [comment]
Notes on Building are obsolete, compilation is now clean.
Bump this up @tomeichlersmith @omar-moreno @pbutti

**Comment by tomeichlersmith** [comment]
## Now
Two annoyances are happening right now which PF would like to get rid of.
1. The tracking geometry needs to be created by every processor that wants to use it even if they are in the same sequence.
2. The detector GDML needs to be copied into the run folder.

## Desired
We'd like to avoid both of these annoyances by integrating the `*TrackingGeometry` classes into the conditions system so that they can be shared across processors and constructed in a uniform manner. An example usage of one of these geometry classes is in `CKFProcessor`

**Comment by omar-moreno** [comment]
This is in progress :)
