### ISSUE TITLE
Processor for tagging "Findable Tracks" 

### ISSUE THREAD

**Issue by omar-moreno** [LDMX-Software/Tracking#17]
This already existed in previous versions of ldmx-sw but needs to be moved here.  This processor will 

* Iterate over all SimTrackerHits
* Associate the SimTrackerHits with their corresponding MC particle
* Determine if that particle is expected to leave a track that should be found by the tracking algorithms.

The resulting "findable tracks" are added as a collection to the event.

**Comment by pbutti** [comment]
@omar-moreno
