### ISSUE TITLE
Smear simulated tracker hits

### ISSUE THREAD

**Issue by omar-moreno** [LDMX-Software/Tracking#4]
Add a processor that smears the simulated hits and creates a new collection.

**Comment by pbutti** [comment]
Hi, 

I made a mistake and already committed this directly to master. 
Issue can be closed as the hit-smearing processor is now in master branch

**Comment by omar-moreno** [comment]
I restricted the branch to prevent this from happening again. Let's leave
the issue until the hit smearing is tested further and some plots can be
posted.

**Comment by pbutti** [comment]
Thank you for restricting.
What plots do you want to see? I think I should be able to produce them between this evening / tomorrow.

**Comment by omar-moreno** [comment]
Hit position residuals would be useful to check that the smearing is
working. Also, did you add the python class needed to run this?

**Comment by pbutti** [comment]
Ok. I will make the position residuals. 
Yes, I've made the python class and I already ran this processor.

**Comment by omar-moreno** [comment]
This issue was resolved by PR #12 .
