### ISSUE TITLE
Update the Measurement class

### ISSUE THREAD

**Issue by omar-moreno** [LDMX-Software/Tracking#45]
The Measurement class can benefit from some updates including:

- [x] A vector of SimParticles used to create the measurement (MC only)
- [x] Documentation 
- [x] Cleanup and clarifications (e.g. Layer vs Layer ID)
- [x] Merge LdmxSpacePoint with Measurement

**Comment by pbutti** [comment]
Hey Omar, 

awesome point. This we really need. I was thinking if we can inherit from this class
https://github.com/pbutti/acts/blob/main/Core/include/Acts/EventData/Measurement.hpp

**Comment by pbutti** [comment]
I opted for storing the trackID vector in the measurement class. See #66. 
Is there a PR to address this issue?

**Comment by pbutti** [comment]
@omar-moreno I think this is completed. Can I close?
